/**
 * RequestController.groovy 
 * Actions over Requestmap objects.
 * @author generated by plugin script
 * @auther Haotian Sun
 */             
class RequestmapController {
  def index = { redirect(action:list,params:params) }

  // the delete, save and update actions only
  // accept POST requests
  def allowedMethods = [delete:'POST',
                        save:'POST',
                        update:'POST']

  def list = {
    if(!params.max)params.max = 10
    [ requestmapList: ${requestmapDomain}.list( params ) ]
  }

  def show = {
    [ requestmap : ${requestmapDomain}.get( params.id ) ]
  }

  def delete = {
    def requestmap = ${requestmapDomain}.get( params.id )
    if(requestmap) {
        requestmap.delete()
        flash.message = "${requestmapDomain} \${params.id} deleted."
        redirect(action:list)
    }
    else {
        flash.message = "${requestmapDomain} not found with id \${params.id}"
        redirect(action:list)
    }
  }

  def edit = {
    def requestmap = ${requestmapDomain}.get( params.id )

    if(!requestmap) {
      flash.message = "${requestmapDomain} not found with id \${params.id}"
      redirect(action:list)
    }
    else {
      return [ requestmap : requestmap ]
    }
  }

  /*update action, called when an existing Requestmap is updated*/
  def update = {
    def requestmap = ${requestmapDomain}.get( params.id )
    if(requestmap) {
      requestmap.properties = params
      //get user's enter field "configAttribute" from the params.
      String[] configAttrs=
                    org.springframework.util.StringUtils.
                    commaDelimitedListToStringArray(params.configAttribute)
      //Format the configAttributes to meet Acegi's requirement.
      String formattedConfigAttrs=""
      for(int i=0; i< configAttrs.length; i++){
	    String configAttribute = configAttrs[i]
	    println configAttribute+"---------"
	    formattedConfigAttrs+="ROLE_"+configAttribute.toUpperCase()+","
	  }
	  requestmap.configAttribute=formattedConfigAttrs
      if(requestmap.save()) {
        redirect(action:show,id:requestmap.id)
      }
      else {
        render(view:'edit',model:[requestmap:requestmap])
      }
    }
    else {
      flash.message = "${requestmapDomain} not found with id \${params.id}"
      redirect(action:edit,id:params.id)
    }
  }

  def create = {
    def requestmap = new ${requestmapDomain}()
    requestmap.properties = params
    return ['requestmap':requestmap]
  }

  /*Save action, called when a new Requestmap is created*/
  def save = {
    def requestmap = new ${requestmapDomain}()
    requestmap.properties = params
    //get user's enter field "configAttribute" from the params.
    String[] configAttrs=
                    org.springframework.util.StringUtils.
                    commaDelimitedListToStringArray(params.configAttribute)
    //Format the configAttributes to meet Acegi's requirement.
    String formattedConfigAttrs=""
    for(int i=0; i< configAttrs.length; i++){
	  String configAttribute = configAttrs[i]
	  println configAttribute+"---------"
	  formattedConfigAttrs+="ROLE_"+configAttribute.toUpperCase()+","
	}
	requestmap.configAttribute=formattedConfigAttrs
    if(requestmap.save()) {
      redirect(action:show,id:requestmap.id)
    }
    else {
      render(view:'create',model:[requestmap:requestmap])
    }
  }

}